<Project Sdk="Atya.Build.Sdk">
  <Import Project="..\..\src\CodeQuality\buildTransitive\Atya.Governance.CodeQuality.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CodeQuality.Sample.Console</RootNamespace>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(EnableWrongStyleExamples)' != 'true'">
    <Compile Remove="WrongStyleExamples\**\*.cs" />
    <None Include="WrongStyleExamples\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\CodeQuality\CodeQuality.csproj" />
  </ItemGroup>
</Project>